// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_q9Q8usjHl56dIc4H9uuAC7bv9qRvzJY',
    appId: '1:211763781904:web:1cf0d79879e9c6bc0a8595',
    messagingSenderId: '211763781904',
    projectId: 'cane-9',
    authDomain: 'cane-9.firebaseapp.com',
    storageBucket: 'cane-9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPn7-spiCwwPrXyAZZt7GipeNKdATA8NI',
    appId: '1:211763781904:android:ab6b7b21bed22ab20a8595',
    messagingSenderId: '211763781904',
    projectId: 'cane-9',
    storageBucket: 'cane-9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqHYmu_b7yTc7Tp9TCal4dm9fGtb4j4s',
    appId: '1:211763781904:ios:a3fb193b7647c2b10a8595',
    messagingSenderId: '211763781904',
    projectId: 'cane-9',
    storageBucket: 'cane-9.appspot.com',
    iosClientId:
        '211763781904-lqullnjjvguieqjgei0pe656fqvpm6jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cane9App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqHYmu_b7yTc7Tp9TCal4dm9fGtb4j4s',
    appId: '1:211763781904:ios:a3fb193b7647c2b10a8595',
    messagingSenderId: '211763781904',
    projectId: 'cane-9',
    storageBucket: 'cane-9.appspot.com',
    iosClientId:
        '211763781904-lqullnjjvguieqjgei0pe656fqvpm6jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cane9App',
  );
}
